export const filters = [
  { id: 1, title: 'Begreber' },
  { id: 2, title: 'Folkeafstemningen' },
  { id: 3, title: 'Partiernes argumenter' },
  { id: 4, title: 'Ja-sidens argumenter' },
  { id: 5, title: 'Nej-sidens argumenter' },
  { id: 6, title: 'Historiske begivenheder' },
  { id: 7, title: 'Retsakter vi får ved ja' },
  { id: 8, title: 'Retsakter vi ikke får ved ja' }
]

export const entries = [
  {
    id: 1, title: 'Hvad er der sket siden \'92?', filterId: 1,
    content: `<p><strong>1. juni 1992</strong><br>
    Et flertal af danskerne (41,7 % mod 40,5 %) stemmer NEJ til Maastrichttraktaten, som ville indebære suverænitetsafgivelse på en række områder, heriblandt dele af retspolitikken.</p>
    <p><strong>18. maj 1993</strong><br>
    Et flertal af danskerne (48,6 % mod 37,0 %) stemmer JA til Edinburghafgørelsen, som Danmark har forhandlet sig frem til med de øvrige EU-lande. Afgørelsen betyder, at Danmark tilslutter sig Maastrichttraktaten med fire forbehold i forhold til forsvar, euro, overstatslig retspolitik og unionsborgerskabet.</p>
    <p><strong>1998-1999</strong><br>
    EU-landene bliver enige om at oprette Europol-samarbejdet i 1998. Det iværksættes året efter og har til formål at bekæmpe grænseoverskridende kriminalitet.</p>
    <p><strong>1. december 2009</strong><br>
    Lissabontraktaten træder i kraft. Det betyder, at alle nye regler på det retspolitiske område fremover bliver overstatslige, og at Danmark derfor ikke vil kunne deltage i disse dele af samarbejdet. Eksisterende mellemstatslige regler bliver ved med at gælde, indtil de afløses af ny overstatslig lovgivning.</p>
    <p><strong>10. december 2014</strong><br>
    Et flertal i Folketinget bestående af Socialdemokraterne, Radikale Venstre, Venstre, Konservative og Socialistisk Folkeparti aftaler at sende det danske EU-retsforbehold til folkeafstemning senest i første kvartal 2016.</p>
    <p><strong>17. marts 2015</strong><br>
    Flertallet indgår en aftale om, hvilke dele af det eksisterende retssamarbejde Danmark skal tilslutte sig, hvis det bliver et ja til folkeafstemningen. Partierne peger på 22 retsakter, mens de fortsat vil stå uden for 10 retsakter foruden retsakterne indenfor asyl- og udlændingeområdet.</p>
    <p><strong>21. august 2015</strong><br>
    Statsminister Lars Løkke Rasmussen (V) udskriver folkeafstemning til afholdelse d. 3. december.</p>
    <p><strong>3. december 2015</strong><br>
    Folkeafstemning om ”Forslag til lov om omdannelse af retsforbeholdet til en tilvalgsordning”.</p>`
  }, {
    id: 2, title: 'Hvad er retsforbeholdet?', filterId: 1,
    content: `<p class="c1"><span>Retsforbeholdet betyder, at Danmark st&aring;r uden for en del af det retlige samarbejde i EU. Det g&aelig;lder blandt andet asyl- og udl&aelig;ndingepolitikken samt de f&aelig;lleseurop&aelig;iske konkurs- og skilsmisseregler. Til geng&aelig;ld har vi i de seneste 16 &aring;r deltaget i det europ&aelig;iske politisamarbejde, Europol, som har til form&aring;l at bek&aelig;mpe gr&aelig;nseoverskridende kriminalitet.</span></p>
    <p class="c1"><span>Retsforbeholdet har v&aelig;ret g&aelig;ldende siden 1993, hvor et flertal af v&aelig;lgerne (56,7 pct.) stemte ja til den s&aring;kaldte Edinburgh-afg&oslash;relse. Den indeb&aelig;rer, at Danmark ogs&aring; har forbehold inden for forsvarssamarbejdet, euroen og unionsborgerskabet. Edinburgh-afg&oslash;relsen blev til som et kompromis mellem Danmark og de &oslash;vrige EU-lande, da et flertal af danskerne (50,7 %) i 1992 havde stemt nej til Maastricht-traktaten.</span></p>`
  }, {
    id: 3, title: 'Hvorfor skal vi til folkeafstemning? ', filterId: 2,
    content: `<p class="c1"><span>Danmark st&aring;r til at ryge ud af det f&aelig;lleseurop&aelig;iske politisamarbejde, Europol, n&aring;r en ny EU-forordning i 2016 ventes at tr&aelig;de i kraft. Det skyldes, at samarbejdet dermed g&aring;r fra at v&aelig;re et s&aring;kaldt</span> <span class="c12">mellem</span><span>statsligt til et</span> <span class="c12">over</span><span>statsligt samarbejde (se nedenfor). &AElig;ndringen sker som konsekvens af Lissabon-traktaten fra 2009, som indeb&aelig;rer at hele det retlige samarbejde p&aring; sigt g&oslash;res overstatsligt. Danmarks EU-forbehold p&aring; retsomr&aring;det betyder, at vi ikke kan deltage i det overstatslige samarbejde.</span></p>
    <p class="c1"><span>Et flertal i Folketinget best&aring;ende af Socialdemokraterne, Radikale Venstre, Venstre, Konservative og Socialistisk Folkeparti blev derfor d. 10. december 2014 enige om at sende det danske EU-forbehold p&aring; retsomr&aring;det til folkeafstemning senest i f&oslash;rste kvartal 2016.</span></p>
    <p class="c1"><span>Efter folketingsvalget d. 18. juni 2015 var der stadig et flertal bag &oslash;nsket om en folkeafstemning. Statsminister Lars L&oslash;kke Rasmussen (V) annoncerede derfor d. 21. august 2015 en folkeafstemning til afholdelse d. 3. december 2015.</span></p>`
  }, {
    id: 4, title: 'Hvad er et mellemstatsligt samarbejde? ', filterId: 1,
    content: `<p class="c1"><span>Et mellemstatsligt samarbejde betyder, at parlamenterne i de enkelte lande skal godkende og implementere EU-reglerne i landenes egen lovgivning. Desuden skal alle medlemslande v&aelig;re enige om nye EU-regler, f&oslash;r de kan vedtages. Patentdomstolen, som var til folkeafstemning i Danmark d. 25. maj 2014, er &eacute;t eksempel p&aring; et mellemstatsligt samarbejde. Den f&aelig;lles udenrigs- og sikkerhedspolitik er et andet.</span></p>
    <p class="c0"><span></span></p>`
  }, {
    id: 5, title: 'Hvad er et overstatsligt samarbejde? ', filterId: 1,
    content: `<p class="c1"><span>Et</span> <span>overstatsligt samarbejde</span><span>&nbsp;betyder derimod, at EU-reglerne har direkte virkning i medlemslandene. Reglerne udarbejdes i samarbejde mellem medlemslandene og Europa-Parlamentet. Med Lissabon-traktaten gik man desuden fra at kr&aelig;ve enstemmighed til flertalsafg&oslash;relser p&aring; det retlige omr&aring;de. EU&rsquo;s samarbejde om blandt andet det indre marked samt landbrugs- og fiskeripolitikken er eksempler p&aring; overstatsligt samarbejde.</span></p>
    <p class="c0"><span></span></p>`
  }, {
    id: 6, title: 'Hvad stemmer vi om? ', filterId: 2,
    content: `<p class="c1"><span>P&aring; stemmesedlen fremg&aring;r titlen p&aring; regeringens lovforslag:</span><span><a class="c4" href="https://www.google.com/url?q=http://www.ft.dk/samling/20151/lovforslag/l29/index.htm&amp;sa=D&amp;usg=AFQjCNEBPSi19cIvQDkehHae1aGJGIKXkQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.ft.dk/samling/20151/lovforslag/l29/index.htm&amp;sa=D&amp;usg=AFQjCNEBPSi19cIvQDkehHae1aGJGIKXkQ">&rdquo;Forslag til lov om omdannelse af retsforbeholdet til en tilvalgsordning&rdquo;</a></span><span>. Vi kan enten krydse JA eller NEJ til, at vi &oslash;nsker denne lov gennemf&oslash;rt.</span></p>
    <p class="c1"><span>Lovens form&aring;l er efter britisk og irsk forbillede at indf&oslash;re en s&aring;kaldt tilvalgsordning, som betyder, at et flertal i Folketinget fremover vil kunne beslutte, om vi skal tilslutte os mere af det f&aelig;lleseurop&aelig;iske retssamarbejde. Som det er i dag, vil sp&oslash;rgsm&aring;let skulle sendes til folkeafstemning, da der er tale om suver&aelig;nitetsafgivelse.</span></p>
    <p class="c1"><span>Udover tilvalgsordningen vil ja-partierne (S+RV+V+K+SF) ogs&aring; tilslutte sig</span><span><a class="c4" href="https://www.google.com/url?q=http://stm.dk/_p_14120.html&amp;sa=D&amp;usg=AFQjCNGHua8E_ZV4fF8wMaQpAFUJugxkmQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://stm.dk/_p_14120.html&amp;sa=D&amp;usg=AFQjCNGHua8E_ZV4fF8wMaQpAFUJugxkmQ">22 eksisterende retsakter</a></span><span>, som Danmark i dag st&aring;r uden for. Det g&aelig;lder blandt andet direktiver om europ&aelig;iske efterforskningskendelser, menneskehandel, seksuelt misbrug af b&oslash;rn og cybercrime.</span></p>
    <p class="c1"><span>10 retsakter inden for strafferet, civilret og familieret &oslash;nsker partierne ikke at tilslutte sig i denne omgang. Derudover er retsakterne p&aring; asyl- og udl&aelig;ndingeomr&aring;det valgt fra.</span></p>
    <p class="c0"><span></span></p>`
  }, {
    id: 7, title: 'Hvad betyder et ja? ', filterId: 2,
    content: `<p class="c1"><span>Et ja betyder, at Danmarks retsforbehold bliver til en s&aring;kaldt tilvalgsordning, som vi ogs&aring; kender den fra Storbritannien og Irland. Vi har if&oslash;lge Lissabontraktaten krav p&aring; at f&aring; en tilvalgsordning p&aring; omr&aring;det. Ordningen vil betyde, at et flertal i Folketinget fremover kan beslutte, hvilke dele af det europ&aelig;iske retssamarbejde, vi &oslash;nsker at deltage i. Ordningen betyder ogs&aring;, at Danmark kan forts&aelig;tte i Europol-samarbejdet, og at vi kan tilslutte os samarbejdet p&aring; 22 omr&aring;der, som vi i dag st&aring;r uden for.</span></p>
    <p class="c1"><span>Et ja betyder desuden, at den f&aelig;lles retspolitik f&aring;r direkte virkning i Danmark. Et tilvalg er</span><span><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/da/spoergsmaal-og-svar-folder/kan-danmark-traekke-et-tilvalg-tilbage&amp;sa=D&amp;usg=AFQjCNHwynrpdkuk92ix-ckauG_Da51Vuw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/da/spoergsmaal-og-svar-folder/kan-danmark-traekke-et-tilvalg-tilbage&amp;sa=D&amp;usg=AFQjCNHwynrpdkuk92ix-ckauG_Da51Vuw">if&oslash;lge Justitsministeriet</a></span><span>&nbsp;bindende, og Danmark vil derfor ikke kunne tr&aelig;kke et tilvalg tilbage. Vi kan dog selv bestemme, om &aelig;ndringer i tilvalgte retsakter skal g&aelig;lde eller ej.</span></p>`
  }, {
    id: 8, title: 'Hvad betyder et nej? ', filterId: 2,
    content: `<p class="c1"><span>Et nej betyder, at det nuv&aelig;rende retsforbehold fastholdes. Danmark st&aring;r derfor til at ryge ud af Europol-samarbejdet, n&aring;r det i 2016 forventes at blive overstatsligt. Hvis Danmark fortsat skal deltage i Europol og andre overstatslige samarbejder, skal vi s&oslash;ge om et f&aring; en s&aring;kaldt parallelaftale.</span></p>
    <p class="c0"><span></span></p>
    <p class="c1"><span>Parallelaftalen skal godkendes af b&aring;de Ministerr&aring;det, Europa-Kommissionen og Europa-Parlamentet. I dag har vi fire parallelaftaler, blandt andet deltager vi i Dublin III-forordningen og Eurodac-forordningen p&aring; asylomr&aring;det, mens vi har f&aring;et afslag p&aring; to parallelaftaler, blandt andet Konkursforordningen. Det er derfor ikke p&aring; forh&aring;nd givet, at vi kan f&aring; en parallelaftale i forhold til eksempelvis Europol.</span></p>`
  }, {
    id: 9, title: 'Hvordan er det g&aring;et til andre EU-afstemninger? ', filterId: 6,
    content: `<p class="c1"><span>25. maj 2014 om</span> <span class="c2">Patentdomstolen</span><span>. 62,5% stemte JA, 37,5% stemte NEJ.<br>
    Valgdeltagelse p&aring; 55,9%.</span></p>
    <p class="c1"><span>28. sep. 2000 om</span> <span class="c2">Euro-deltagelse</span><span>. 46,8% stemte JA, 53,2% stemte NEJ.<br>
    Valgdeltagelse p&aring; 87,6%.</span></p>
    <p class="c1"><span>28. maj 1998 om</span> <span class="c2">Amsterdamtraktaten</span><span>. 55,1% stemte JA. 44,9% stemte NEJ.<br>
    Valgdeltagelse p&aring; 76,2%.</span></p>
    <p class="c1"><span>18. maj 1993 om</span> <span class="c2">Edinburghafg&oslash;relsen (EU-forbehold)</span><span>. 56,7% stemte JA. 43,3% stemte NEJ.<br>
    Valgdeltagelse p&aring; 86,5%.</span></p>
    <p class="c1"><span>2. juni 1992 om</span> <span class="c2">Maastrichttraktaten</span><span>. 49,3% stemte JA. 50,7% stemte NEJ.<br>
    Valgdeltagelse p&aring; 83,1%.</span></p>
    <p class="c1"><span>27. feb. 1986 om</span> <span class="c2">EF-pakken (blandt andet etablering af indre marked)</span><span>. 56,2% stemte JA. 43,8% stemte NEJ.<br>
    Valgdeltagelse p&aring; 75,4%.</span></p>
    <p class="c1"><span>2. okt. 1972 om</span> <span class="c2">EF-tiltr&aelig;delse</span><span>. 63,3% stemte JA. 36,7% stemte NEJ.<br>
    Valgdeltagelse p&aring; 90,1%.</span></p>`
  }, {
    id: 10, title: 'Socialdemokraterne siger JA ', filterId: 3,
    content: `<p class="c1"><span>Socialdemokraterne anbefaler et JA til folkeafstemningen. Hovedargumentet er if&oslash;lge</span><span><a class="c4" href="https://www.google.com/url?q=http://www.socialdemokraterne.dk/da/politik/retsforbehold/&amp;sa=D&amp;usg=AFQjCNGDhfJs65fV3dAzUETyFNEHhcTNEw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.socialdemokraterne.dk/da/politik/retsforbehold/&amp;sa=D&amp;usg=AFQjCNGDhfJs65fV3dAzUETyFNEHhcTNEw">partiets hjemmeside</a></span><span>, at Danmark fortsat skal v&aelig;re en del af Europol-samarbejdet. Til geng&aelig;ld vil Socialdemokraterne ikke tilslutte sig den f&aelig;lles asyl- og udl&aelig;ndingepolitik.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Socialdemokraterne &oslash;nsker udover retsforbeholdet ogs&aring; at afskaffe forsvarsforbeholdet. Det fremg&aring;r af den tidligere regerings</span><span><a class="c4" href="https://www.google.com/url?q=http://www.stm.dk/publikationer/Et_Danmark_der_staar_sammen_11/Regeringsgrundlag_okt_2011.pdf&amp;sa=D&amp;usg=AFQjCNF-feZbeU3Zg36r41qWrVj6jAHMog">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.stm.dk/publikationer/Et_Danmark_der_staar_sammen_11/Regeringsgrundlag_okt_2011.pdf&amp;sa=D&amp;usg=AFQjCNF-feZbeU3Zg36r41qWrVj6jAHMog">regeringsgrundlag</a></span><span>. Derudover mener partiet som udgangspunkt, at Danmark b&oslash;r deltage i</span><span><a class="c4" href="https://www.google.com/url?q=http://www.politiko.dk/nyheder/regeringen-vil-have-danmark-med-i-europaeisk-bankunion&amp;sa=D&amp;usg=AFQjCNHP0wiDI2KZLaxk5u1CXfRt4JjPtA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.politiko.dk/nyheder/regeringen-vil-have-danmark-med-i-europaeisk-bankunion&amp;sa=D&amp;usg=AFQjCNHP0wiDI2KZLaxk5u1CXfRt4JjPtA">den f&aelig;lles bankunion</a></span><span>.</span></p>
    <p class="c0"><span></span></p>`
  }, {
    id: 11, title: 'Venstre siger JA ', filterId: 3,
    content: `<p class="c1"><span>Venstre anbefaler et JA til folkeafstemningen. I</span><span><a class="c4" href="https://www.google.com/url?q=http://www.venstre.dk/_Resources/Persistent/63002ee09c17ea437981728a5d7f2402e4c472d9/Regeringsgrundlag-2015.pdf&amp;sa=D&amp;usg=AFQjCNHdrjVfaZy8DpahLWsvEfayVevOOA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.venstre.dk/_Resources/Persistent/63002ee09c17ea437981728a5d7f2402e4c472d9/Regeringsgrundlag-2015.pdf&amp;sa=D&amp;usg=AFQjCNHdrjVfaZy8DpahLWsvEfayVevOOA">regeringsgrundlaget</a></span><span>&nbsp;n&aelig;vnes Europol-samarbejdet som den prim&aelig;re &aring;rsag til at opgive retsforbeholdet. Statsminister Lars L&oslash;kke Rasmussen har desuden fra Folketingets talerstol</span><span><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/loekke-lover-danskerne-kun-i-kan-sige-ja-til-europaeisk-asylpolitik&amp;sa=D&amp;usg=AFQjCNGklyfHuducASLMZ9KDKhZ1FRpneQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/loekke-lover-danskerne-kun-i-kan-sige-ja-til-europaeisk-asylpolitik&amp;sa=D&amp;usg=AFQjCNGklyfHuducASLMZ9KDKhZ1FRpneQ">givet en garanti for</a></span><span>, at han vil udskrive endnu en folkeafstemning, hvis et flertal i Folketinget p&aring; et senere tidspunkt &oslash;nsker at tilslutte sig den f&aelig;lles asyl- og udl&aelig;ndingepolitik. Denne garanti fremg&aring;r ogs&aring; af bem&aelig;rkningerne i et &aelig;ndringsforslag til lovforslaget fremsat af udenrigsministeren, hvor V, S og KF sl&aring;r fast, at de vil kr&aelig;ve en folkeafstemning f&oslash;r de opgiver deres veto p&aring; asyl- og indvandringsomr&aring;det.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Venstre er en varm tilh&aelig;nger af EU-samarbejdet, men det skal</span><span><a class="c4" href="https://www.google.com/url?q=http://stm.dk/multimedia/Regeringsgrundlag_2016.pdf&amp;sa=D&amp;usg=AFQjCNE0hPDOCoYa2jU_tuFej8PtaKIVvQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://stm.dk/multimedia/Regeringsgrundlag_2016.pdf&amp;sa=D&amp;usg=AFQjCNE0hPDOCoYa2jU_tuFej8PtaKIVvQ">if&oslash;lge regeringsgrundlaget</a></span><span>&nbsp;v&aelig;re et mere &rdquo;st&aelig;rkt, slankt og effektivt EU, der respekterer n&aelig;rhedsprincippet og koncentrerer sig om de udfordringer, som medlemslandene bedst kan l&oslash;se i f&aelig;llesskab&rdquo;. Venstre vil derfor fokusere p&aring; at styrke det indre marked, videreudvikle EU&rsquo;s handelsaftaler og &oslash;ge konkurrenceevnen ved hj&aelig;lp af strukturreformer. Derimod skal EU ikke v&aelig;re en social union.</span></p>`
  }, {
    id: 12, title: 'Radikale Venstre siger JA ', filterId: 3,
    content: `<p class="c1"><span>Radikale Venstre anbefaler et JA til folkeafstemningen.</span><span><a class="c4" href="https://www.google.com/url?q=https://www.radikale.dk/content/eu&amp;sa=D&amp;usg=AFQjCNEd4SAQSTrjJX_SMRqYoToF-43Hyw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=https://www.radikale.dk/content/eu&amp;sa=D&amp;usg=AFQjCNEd4SAQSTrjJX_SMRqYoToF-43Hyw">Partiet &oslash;nsker</a></span><span>&nbsp;desuden at deltage i den f&aelig;lles asylpolitik i EU, men har indg&aring;et en aftale med de &oslash;vrige ja-partier om, at partierne skal v&aelig;re enige, f&oslash;r det kan ske.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Radikale Venstre &oslash;nsker, at Danmark kommer</span><span><a class="c4" href="https://www.google.com/url?q=https://www.radikale.dk/content/eu&amp;sa=D&amp;usg=AFQjCNEd4SAQSTrjJX_SMRqYoToF-43Hyw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=https://www.radikale.dk/content/eu&amp;sa=D&amp;usg=AFQjCNEd4SAQSTrjJX_SMRqYoToF-43Hyw">&rdquo;fuldt og helt med i EU&rdquo;</a></span><span>. Partiet vil derfor afskaffe alle Danmarks EU-forbehold og deltage i den europ&aelig;iske bankunion. Partiet &oslash;nsker et t&aelig;ttere EU-samarbejde p&aring; s&aelig;rligt omr&aring;der som &rdquo;infrastruktur, forskning, uddannelse og gr&oslash;n omstilling&rdquo;.</span></p>`
  }, {
    id: 13, title: 'SF siger JA ', filterId: 3,
    content: `<p class="c1"><span>Socialistisk Folkeparti anbefaler et JA til folkeafstemningen. Retsforbeholdet betyder</span><span><a class="c4" href="https://www.google.com/url?q=http://sf.dk/det-vil-vi/danmark-i-verden/eu&amp;sa=D&amp;usg=AFQjCNHePyCFA_wuaqZsDDVjk4JeoAfpMw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://sf.dk/det-vil-vi/danmark-i-verden/eu&amp;sa=D&amp;usg=AFQjCNHePyCFA_wuaqZsDDVjk4JeoAfpMw">if&oslash;lge partiets hjemmeside</a></span><span>, at Danmark i dag er uden for indflydelse, n&aring;r det g&aelig;lder det f&aelig;lles politisamarbejde. Med en tilvalgsordning f&aring;r vi mulighed for at sidde med ved bordet, n&aring;r beslutningerne tr&aelig;ffes.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>SF vil afskaffe b&aring;de rets- og forsvarsforbeholdet, men &oslash;nsker fortsat at st&aring; uden for euroen. Derudover mener partiet</span><span><a class="c4" href="https://www.google.com/url?q=http://sf.dk/det-vil-vi/danmark-i-verden/eu&amp;sa=D&amp;usg=AFQjCNHePyCFA_wuaqZsDDVjk4JeoAfpMw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://sf.dk/det-vil-vi/danmark-i-verden/eu&amp;sa=D&amp;usg=AFQjCNHePyCFA_wuaqZsDDVjk4JeoAfpMw">if&oslash;lge sin hjemmeside</a></span><span>, at Danmark skal presse p&aring; for, at EU i endnu h&oslash;jere grad &rdquo;bek&aelig;mper fattigdom, arbejder for en f&aelig;lles indsats mod klimatruslen, sikrer ordentlige arbejdsvilk&aring;r for l&oslash;nmodtagere og effektivt bek&aelig;mper international kriminalitet&rdquo;.</span></p>`
  }, {
    id: 14, title: 'Konservative siger JA ', filterId: 3,
    content: `<p class="c1"><span>Konservative anbefaler et JA til folkeafstemningen. Retsforbeholdet har</span><span><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/retsforbeholdet-til-afstemning-her-staar-dit-parti&amp;sa=D&amp;usg=AFQjCNG2yG4BjqHG_p7goqbL1Oug2oDTrA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/retsforbeholdet-til-afstemning-her-staar-dit-parti&amp;sa=D&amp;usg=AFQjCNG2yG4BjqHG_p7goqbL1Oug2oDTrA">if&oslash;lge partileder S&oslash;ren Pape Poulsen</a></span><span>&nbsp;gjort det &rdquo;vanskeligere at bek&aelig;mpe den stigende gr&aelig;nseoverskridende kriminalitet i Europa&rdquo;. Europol-samarbejdet er derfor ogs&aring; det vigtigste argument for Konservative.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Konservative &oslash;nsker</span><span><a class="c4" href="https://www.google.com/url?q=http://www.konservative.dk/Politik/Europapolitik/Europapolitik&amp;sa=D&amp;usg=AFQjCNEz2L6LhNiWr1M4yB_ZJV6eMiX9sQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.konservative.dk/Politik/Europapolitik/Europapolitik&amp;sa=D&amp;usg=AFQjCNEz2L6LhNiWr1M4yB_ZJV6eMiX9sQ">if&oslash;lge sin hjemmeside</a></span><span>&nbsp;at afskaffe b&aring;de rets- og forsvarsforbeholdet. Partiet &oslash;nsker som udgangspunkt ogs&aring; at tilslutte sig euroen, men mener ikke, at tiden er moden endnu. Derudover vil Konservative styrke EU inden for s&aelig;rligt v&aelig;kst og arbejdsskabelse, mens blandt andet kultur, folkeskole, sundhed, socialpolitik og skattepolitik fortsat skal v&aelig;re et nationalt anliggende.</span></p>`
  }, {
    id: 15, title: 'Alternativet siger JA ', filterId: 3,
    content: `<p class="c1"><span>Alternativet anbefaler et JA til folkeafstemningen. If&oslash;lge</span><span><a class="c4" href="https://www.google.com/url?q=http://www.politiko.dk/nyheder/alternativet-siger-nej-til-at-lege-med-ja-partierne&amp;sa=D&amp;usg=AFQjCNHd60-Ed0xqKeYmNGt406RWzlZcNA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.politiko.dk/nyheder/alternativet-siger-nej-til-at-lege-med-ja-partierne&amp;sa=D&amp;usg=AFQjCNHd60-Ed0xqKeYmNGt406RWzlZcNA">politisk ordf&oslash;rer Rasmus Nordqvist</a></span><span>&nbsp;vil partiet ogs&aring; gerne tilslutte sig den f&aelig;lles asyl- og flygtningepolitik. Alternativet er dog kritisk over for tilvalgsordningen, fordi den vil give en sn&aelig;ver kreds af partier mulighed for at indg&aring; aftaler uden at sp&oslash;rge danskerne. Derfor er partiet ikke en del af forligskredsen bag folkeafstemningen.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Alternativet</span><span><a class="c4" href="https://www.google.com/url?q=http://alternativet.dk/alternativet-anbefaler-et-ja-men-til-kommende-eu-folkeafstemning/&amp;sa=D&amp;usg=AFQjCNE6VC26VujBY1KCsCWJSKha2DYQJw">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://alternativet.dk/alternativet-anbefaler-et-ja-men-til-kommende-eu-folkeafstemning/&amp;sa=D&amp;usg=AFQjCNE6VC26VujBY1KCsCWJSKha2DYQJw">betegner sig selv</a></span><span>&nbsp;om &rdquo;et EU-positivt, kritisk parti, der tror p&aring;, at de udfordringer som Danmark og verden st&aring;r over for, er s&aring; store, at det kr&aelig;ver globale b&aelig;redygtige l&oslash;sninger at h&aring;ndtere dem&rdquo;. Alternativet vil</span><span><a class="c4" href="https://www.google.com/url?q=http://alternativet.dk/website/wp-content/uploads/2014/06/Partiprogram_1.3_04.15.pdf&amp;sa=D&amp;usg=AFQjCNFqsjaBFlnrTy3YOhm3ZUv2Xfm2eA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://alternativet.dk/website/wp-content/uploads/2014/06/Partiprogram_1.3_04.15.pdf&amp;sa=D&amp;usg=AFQjCNFqsjaBFlnrTy3YOhm3ZUv2Xfm2eA">if&oslash;lge sit partiprogram</a></span><span>&nbsp;arbejde p&aring;, &rdquo;at b&aelig;redygtighed bliver prioriteret h&oslash;jere end &oslash;konomisk v&aelig;kst&rdquo; i EU-samarbejdet.</span></p>`
  }, {
    id: 16, title: 'Dansk Folkeparti siger NEJ ', filterId: 3,
    content: `<p class="c1"><span>Dansk Folkeparti anbefaler et NEJ til folkeafstemningen. Partiet frygter</span><span><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/nej-partier-kritiserer-europol-snak-gidsel-i-debatten-beskidt-trick-og-taet-paa&amp;sa=D&amp;usg=AFQjCNEo7cPB9SBiz40lz7QKIWAZ-yemzA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.dr.dk/nyheder/politik/nej-partier-kritiserer-europol-snak-gidsel-i-debatten-beskidt-trick-og-taet-paa&amp;sa=D&amp;usg=AFQjCNEo7cPB9SBiz40lz7QKIWAZ-yemzA">if&oslash;lge udenrigsordf&oslash;rer S&oslash;ren Espersen</a></span><span>, at ja-partierne p&aring; et senere tidspunkt vil udnytte en tilvalgsordning til at tilslutte sig den f&aelig;lles asyl- og udl&aelig;ndingepolitik uden at sp&oslash;rge danskerne. Til geng&aelig;ld vil Dansk Folkeparti</span><span><a class="c4" href="https://www.google.com/url?q=http://www.danskfolkeparti.dk/Europol_som_l%2525C3%2525B8ftestang__Nej_%2525C3%2525A6rlighed_i_EU-politikken_tak_&amp;sa=D&amp;usg=AFQjCNGSGz3eWsk_c2zmGMYVGx5WL-ZCFA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.danskfolkeparti.dk/Europol_som_l%2525C3%2525B8ftestang__Nej_%2525C3%2525A6rlighed_i_EU-politikken_tak_&amp;sa=D&amp;usg=AFQjCNGSGz3eWsk_c2zmGMYVGx5WL-ZCFA">if&oslash;lge partiformand Kristian Thulesen Dahl</a></span><span>&nbsp;indg&aring; en s&aring;kaldt parallelaftale med de &oslash;vrige europ&aelig;iske lande, s&aring; Danmark fortsat kan v&aelig;re en del af Europol.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Dansk Folkeparti &oslash;nsker ikke at melde sig ud af EU, men &oslash;nsker</span><span><a class="c4" href="https://www.google.com/url?q=http://www.transparens.eu/&amp;sa=D&amp;usg=AFQjCNFE3KdAE2yxAFVf4PkTkVIGc1dkGA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.transparens.eu/&amp;sa=D&amp;usg=AFQjCNFE3KdAE2yxAFVf4PkTkVIGc1dkGA">if&oslash;lge sin hjemmeside</a></span><span>&nbsp;&rdquo;fundamentale forandringer i den m&aring;de, hvor landene samarbejde inden for EU&rdquo;. Partiet &oslash;nsker at begr&aelig;nse EU&rsquo;s magt og vil indf&oslash;re flere danske forbehold i forhold til &rdquo;velf&aelig;rdspolitik, gr&aelig;nsekontrol og udl&aelig;ndingepolitik&rdquo;. EU-samarbejdet skal begr&aelig;nses til omr&aring;der som</span><span><a class="c4" href="https://www.google.com/url?q=http://www.danskfolkeparti.dk/M%25C3%25A6rkesag-EU&amp;sa=D&amp;usg=AFQjCNF6die_Q24UUt583xQpA_iWmBl6OQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.danskfolkeparti.dk/M%25C3%25A6rkesag-EU&amp;sa=D&amp;usg=AFQjCNF6die_Q24UUt583xQpA_iWmBl6OQ">handelspolitik, milj&oslash;politik og teknisk samarbejde</a></span><span>.</span></p>`
  }, {
    id: 17, title: 'Liberal Alliance siger NEJ ', filterId: 3,
    content: `<p class="c1"><span>Liberal Alliance anbefaler et NEJ til folkeafstemningen. If&oslash;lge tidligere EU-ordf&oslash;rer Mette Bock vil tilvalgsordningen blive</span><span><a class="c4" href="https://www.google.com/url?q=https://www.liberalalliance.dk/pressemeddelelse/press_newsletter-live_1714&amp;sa=D&amp;usg=AFQjCNF2ay573jv7KC-xqr5qkGDU6yz24g">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=https://www.liberalalliance.dk/pressemeddelelse/press_newsletter-live_1714&amp;sa=D&amp;usg=AFQjCNF2ay573jv7KC-xqr5qkGDU6yz24g">en &rdquo;glidebane&rdquo;</a></span><span>, som vil give skiftende politiske flertal mulighed for at til- og frav&aelig;lge uden at sp&oslash;rge danskerne. Liberal Alliance vil dog ogs&aring; fors&oslash;ge at lave en parallelaftale med de &oslash;vrige lande om at deltage i Europol.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Liberal Alliance vil</span><span><a class="c4" href="https://www.google.com/url?q=https://www.liberalalliance.dk/la/eu-fred-og-frihandel/&amp;sa=D&amp;usg=AFQjCNGE5lciknWs7fkwa53rkmYBqyipSg">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=https://www.liberalalliance.dk/la/eu-fred-og-frihandel/&amp;sa=D&amp;usg=AFQjCNGE5lciknWs7fkwa53rkmYBqyipSg">if&oslash;lge sin hjemmeside</a></span><span>&nbsp;afskaffe forsvarsforbeholdet, men &oslash;nsker at bevare retsforbeholdet og st&aring; uden for euroen. Partiet &oslash;nsker, at EU vender &rdquo;tilbage til sit egentlige form&aring;l, nemlig at sikre frihed for borgere, virksomheder, civilsamfund og medlemsstater&rdquo;. Det vil sige, at partiet &oslash;nsker et styrket indre marked, mens EU skal begr&aelig;nses i at lave forbud og regler, &rdquo;der detailstyrer borgernes privatliv&rdquo;.</span></p>`
  }, {
    id: 18, title: 'Enhedslisten siger NEJ ', filterId: 3,
    content: `<p class="c1"><span>Enhedslisten anbefaler et NEJ til folkeafstemningen. Partiet mener</span><span><a class="c4" href="https://www.google.com/url?q=https://enhedslisten.dk/artikel/enhedslisten-til-eu-partierne-vaer-aerlig-om-retsforbeholdet-74521&amp;sa=D&amp;usg=AFQjCNGKuIDFdaxFXs9z6o6rX6BrCeyaPA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=https://enhedslisten.dk/artikel/enhedslisten-til-eu-partierne-vaer-aerlig-om-retsforbeholdet-74521&amp;sa=D&amp;usg=AFQjCNGKuIDFdaxFXs9z6o6rX6BrCeyaPA">if&oslash;lge retsordf&oslash;rer Pernille Skipper</a></span><span>, at en afskaffelse af retsforbeholdet vil give EU mulighed for at bestemme over den danske retspolitik. Ligesom Dansk Folkeparti og Liberal Alliance mener Enhedslisten, at Danmark kan indg&aring; en parallelaftale om deltagelse i Europol.</span></p>
    <p class="c1"><span class="c2">Generel EU-holdning:</span> <span>Enhedslisten &oslash;nsker</span><span><a class="c4" href="https://www.google.com/url?q=http://enhedslisten.dk/artikel/nej-til-eu-ja-til-internationalt-samarbejde&amp;sa=D&amp;usg=AFQjCNF25bH33JCy2dto85rDfX8LrN2j_w">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://enhedslisten.dk/artikel/nej-til-eu-ja-til-internationalt-samarbejde&amp;sa=D&amp;usg=AFQjCNF25bH33JCy2dto85rDfX8LrN2j_w">if&oslash;lge sin hjemmeside</a></span><span>&nbsp;som det eneste parti i Folketinget at melde Danmark helt ud af EU. Partiet mener, at &rdquo;EU bygger p&aring; et grundlag, der s&aelig;tter markedet over sundhed, milj&oslash;, faglige rettigheder og velf&aelig;rd&rdquo;. Enhedslisten vil i stedet skabe et &rdquo;anderledes socialt, b&aelig;redygtigt og demokratisk samarbejde&rdquo; med venstrefl&oslash;jspartier i resten af Europa.</span></p>`
  }, {
    id: 19, title: 'Danmark ryger ud af Europol, hvis vi beholder retsforbeholdet', filterId: 4,
    content: `<p>Fakta: Danmark ryger kun ud af Europol, hvis vi IKKE får forhandlet en parallelaftale på plads. Vi har dog ikke juridisk krav på en parallelaftale, som vi har på en tilvalgsordning.</p>`
  }, {
    id: 20, title: 'Tilvalgsordningen giver valgfrihed, s&aring; Danmark kan deltage i de dele, vi &oslash;nsker, og st&aring; uden for de dele, vi ikke &oslash;nsker ', filterId: 4,
    content: `<p class="c1"><span>Fakta: Det er korrekt. Men overgangen til en tilvalgsordning vil</span><span><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/en-trovaerdig-nej-alliance&amp;sa=D&amp;usg=AFQjCNH0Gdh9uNxYQWS3_9GoNno2SjIXjg">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/en-trovaerdig-nej-alliance&amp;sa=D&amp;usg=AFQjCNH0Gdh9uNxYQWS3_9GoNno2SjIXjg">if&oslash;lge T&aelig;nketanken Europa</a></span><span>&nbsp;betyde, at Danmark er EU-retligt forpligtet til at tilv&aelig;lge alle de retsakter under Schengensamarbejdet, som vi i forvejen er en del af. Det fremg&aring;r af protokollen om Danmarks stilling, art. 8, stk. 2.</span></p>
    <p class="c1"><span>Det er ogs&aring; v&aelig;rd at bem&aelig;rke, at tilvalg er bindende. Danmark er ikke forpligtet til at tilv&aelig;lge nye, &aelig;ndrede udgaver af tilvalgte retsakter. Et manglende tilvalg fra Danmark giver dog EU mulighed for at sende Danmark ud af den oprindelige retsakt.</span></p>`
  }, {
    id: 21, title: 'Danmark vil fortsat st&aring; uden for den f&aelig;lles asyl- og udl&aelig;ndingepolitik ', filterId: 4,
    content: `<p class="c1"><span>Fakta: Det er korrekt, at vi ikke tilslutter os flere dele af asyl- og udl&aelig;ndingepolitikken. Vi har dog allerede i dag parallelaftaler p&aring; to omr&aring;der: Dublin III-forordningen, som bestemmer, hvor asylans&oslash;gninger skal behandles, og Eurodac-forordningen, som omhandler registrering af asylans&oslash;geres fingeraftryk.</span></p>`
  }, {
    id: 22, title: 'De 22 nye retsakter indeholder alle konkrete forbedringer for borgere og virksomheder ', filterId: 4,
    content: `<p class="c1"><span>Fakta: Det er i hvert fald konklusionen i det</span><span><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/~/media/aftale_om_tilvalg_af_retsakter.ashx&amp;sa=D&amp;usg=AFQjCNGmTdDgY2pnz5T8cFd34hUKXu9dnQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/~/media/aftale_om_tilvalg_af_retsakter.ashx&amp;sa=D&amp;usg=AFQjCNGmTdDgY2pnz5T8cFd34hUKXu9dnQ">analysearbejde</a></span><span>, der ligger til grund for ja-partiernes tilslutning til de 22 retsakter. Nej-partierne</span><span><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/~/media/files/eu/faelles_aftale_om_aabenhed_i_retspolitikken.ashx&amp;sa=D&amp;usg=AFQjCNG3ofgFaNB3wOHi-pdHQU27Kx-nqg">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://www.eu.dk/~/media/files/eu/faelles_aftale_om_aabenhed_i_retspolitikken.ashx&amp;sa=D&amp;usg=AFQjCNG3ofgFaNB3wOHi-pdHQU27Kx-nqg">h&aelig;vder dog</a></span><span>, at analysen ikke kan &rdquo;betragtes som objektiv eller politisk uafh&aelig;ngig&rdquo;, fordi en politisk f&oslash;lgegruppe l&oslash;bende har givet indspark til embedsapparatets arbejde.</span></p>`
  }, {
    id: 23, title: 'Danskerne bliver spurgt igen, f&oslash;r vi tilslutter os mere af den f&aelig;lles asyl- og udl&aelig;ndingepolitik ', filterId: 4,
    content: `<p class="c1"><span>Fakta: Det har statsminister Lars L&oslash;kke Rasmussen (V) lovet fra Folketingets talerstol. Denne garanti fremg&aring;r ogs&aring; af bem&aelig;rkningerne i et &aelig;ndringsforslag til lovforslaget fremsat af udenrigsministeren, hvor V, S og KF sl&aring;r fast, at de vil kr&aelig;ve en folkeafstemning f&oslash;r de opgiver deres veto p&aring; asyl- og indvandringsomr&aring;det.</span></p>
    <p class="c1"><span>I ja-partiernes</span><span><a class="c4" href="https://www.google.com/url?q=http://stm.dk/_p_14101.html&amp;sa=D&amp;usg=AFQjCNHlGaKXR_3X_fPS1LKE2xUVkP5ZTA">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://stm.dk/_p_14101.html&amp;sa=D&amp;usg=AFQjCNHlGaKXR_3X_fPS1LKE2xUVkP5ZTA">aftale</a></span><span>&nbsp;er der ogs&aring; indskrevet en vetomodel for netop dette omr&aring;de (pkt. 5). I forhold til de &oslash;vrige 10 eksisterende og for indev&aelig;rende fravalgte retsakter inden for strafferet, civilret og familieret fremg&aring;r det, at &rdquo;s&aring;fremt aftalepartierne senere m&aring;tte &oslash;nske at tilv&aelig;lge s&aring;danne retsakter, kan det kun ske ved enighed blandt aftalepartierne eller ved, at det annonceres forud for et folketingsvalg&rdquo;. &nbsp;</span></p>`
  }, {
    id: 24, title: 'Danmark ryger ikke ud af Europol, hvis vi indg&aring;r en parallelaftale som Norge, Island og Schweiz ', filterId: 5,
    content: `<p class="c1"><span>Fakta: Det er korrekt, hvis det lykkes os at indg&aring; en parallelaftale. Vi har dog ikke juridisk krav p&aring; en aftale. I dag har vi fire parallelaftaler, mens vi har f&aring;et afslag p&aring; to andre aftaler. Begge afslag er givet f&oslash;r Lissabontraktaten tr&aring;dte i kraft i 2009 og dermed f&oslash;r Danmark fik mulighed for at overg&aring; til en tilvalgsordning. Desuden har eksempelvis Norge, der har en operationel aftale med Europol og ikke en parallelaftale,</span><span><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/norsk-model-vil-vaere-en-haemsko-dansk-politi&amp;sa=D&amp;usg=AFQjCNFc91THbtLUwWXP0X9YW2_HIII8oQ">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/norsk-model-vil-vaere-en-haemsko-dansk-politi&amp;sa=D&amp;usg=AFQjCNFc91THbtLUwWXP0X9YW2_HIII8oQ">if&oslash;lge T&aelig;nketanken Europa</a></span><span>&nbsp;ikke helt lige s&aring; gode arbejdsbetingelser i Europol.</span></p>`
  }, {
    id: 25, title: 'Vi kan alternativt udnytte en begr&aelig;nset tilvalgsordning, hvor EU overlades retspolitiske bef&oslash;jelser p&aring; et n&aelig;rmere afgr&aelig;nset omr&aring;de ', filterId: 5,
    content: `<p class="c1"><span>Fakta: Det er en mulighed, men det vil</span><span><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/en-trovaerdig-nej-alliance&amp;sa=D&amp;usg=AFQjCNH0Gdh9uNxYQWS3_9GoNno2SjIXjg">&nbsp;</a></span><span class="c3"><a class="c4" href="https://www.google.com/url?q=http://thinkeuropa.dk/politik/en-trovaerdig-nej-alliance&amp;sa=D&amp;usg=AFQjCNH0Gdh9uNxYQWS3_9GoNno2SjIXjg">if&oslash;lge T&aelig;nketanken Europa</a></span><span>&nbsp;betyde, at Danmark er EU-retligt forpligtet til samtidig at tilv&aelig;lge alle de retsakter under Schengensamarbejdet, som vi i forvejen er en del af (se protokol 22, art. 8, stk. 2.). Det er Dansk Folkeparti ellers modstander af.</span></p>`
  }, {
    id: 26, title: 'Hvis vi f&aring;r en tilvalgsordning, vil et flertal i Folketinget kunne beslutte, at Danmark skal deltage i mere af det retspolitiske samarbejde, uden at danskerne bliver spurgt ', filterId: 5,
    content: `<p class="c1"><span>Fakta: Ja, en tilvalgsordning vil formelt betyde, at der fremover blot skal et simpelt flertal til i Folketinget, hvis Danmark skal tilslutte sig flere retsakter p&aring; omr&aring;det. Fsva. asyl og indvandringspolitikken fremg&aring;r det dog af lovforslaget, at det vil kr&aelig;ve en ny folkeafstemning. Fsva. de 10 fravalgte retsakter har de fem ja-partier dog aftalt, at de enten alle skal v&aelig;re enige om det eller annoncere det f&oslash;r et folketingsvalg.</span></p>`
  }, {
    id: 27, title: 'Hvad er 30%-reglen? (Filter: 1)', filterId: 1,
    content: `<p class="c1"><span>Det er ikke n&oslash;dvendigvis tilstr&aelig;kkeligt, at et flertal af v&aelig;lgerne stemmer nej, hvis lovforslaget skal forkastes. If&oslash;lge grundlovens &sect; 42, stk. 5, kr&aelig;ver det nemlig, at mindst 30 procent af samtlige stemmeberettigede stemmer imod lovforslaget. Teoretisk set kan lovforslaget alts&aring; godt blive vedtaget, selvom et flertal stemmer nej. Det kr&aelig;ver dog, at valgdeltagelsen er ret lav.</span></p>
    <p class="c1"><span>Antallet af stemmeberettigede offentligg&oslash;res af Social- og Indenrigsministeriet flere gange op til valget. Det endelige tal opgives f&oslash;rst efter valget, da man f&oslash;rst efterf&oslash;lgende kan vide, hvor mange som er d&oslash;de p&aring; dagen og derfor ikke skal t&aelig;lles med. Ved FV15 var der 4.145.105 stemmeberettigede. Hvis vi tager udgangspunkt i det tal, skal der 1.243.532 nej-stemmer til for at forkaste lovforslaget. Statsministeren har dog givet udtryk for, at han vil acceptere afstemningsresultatet lige meget hvad.</span></p>`
  }
]
